# Generated by Django 6.0.5 on 2026-05-20 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место для выполнения привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                ("time", models.TimeField(help_text="Укажите время для выполнения привычки", verbose_name="Время")),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действия для выполнения привычки", max_length=255, verbose_name="Действие"
                    ),
                ),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность привычки в днях",
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "duration",
                    models.DurationField(
                        help_text="Сколько секунд вы хотите тратить на привычку", verbose_name="Время на выполнение"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичность")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
