# Generated by Django 6.0.5 on 2026-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(verbose_name="Время на выполнение"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Место"),
        ),
    ]
